name: birthday reminder
 
on:
    push:
        branches:
            - master
    schedule:
        - cron: '0 1 * * *'
env:
    TZ: Asia/Shanghai

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
            - uses: actions/setup-go@v2
              with:
                go-version: '^1.14'
            - run: go run main.go -sckey ${{ secrets.SCKEY }}